# Data can be loaded using this tutorial https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html

version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
    environment:
     - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - 5601:5601
    depends_on: ['elasticsearch']