# https://guacamole.apache.org/doc/gug/guacamole-docker.html

version: '3'

services:
  # Some configuration of the database will be nessary
  db:
    image: postgres:9.6
    restart: unless-stopped 
    hostname: db
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_usr
      POSTGRES_PASSWORD: guacamole_pass
    networks:
      - guac

  guacd:
    image: guacamole/guacd
    restart: unless-stopped 
    hostname: guacd
    networks:
      - guac

  # http://localhost:8080/guacamole/
  web:
    image: guacamole/guacamole
    ports: 
      - "8080:8080"
    restart: unless-stopped 
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_usr
      POSTGRES_PASSWORD: guacamole_pass
      GUACD_HOSTNAME: guacd
    networks:
      - guac
    depends_on:
      - db
      - guacd

networks:
  guac:
    driver: bridge
