# Data can be loaded using this tutorial https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html

version: '3.1'

services:
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"

  kudu:
    build: ./kudu
    ports: 
      - "8051:8051"
      - "7051:7051"
      - "8050:8050"

  spark:
    build: ./spark 
    volumes:
      - ./spark/data:/home/data/
    stdin_open: true
    tty: true
