# Data can be loaded using this tutorial https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html

version: '3.1'

services:
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"

  # kudu-master:
  #   build: ./kudu
  #   ports: 
  #     - "8051:8051"
  #   stdin_open: true
  #   tty: true
  #   #command: service kudu-master start

  # kudu-tablet:
  #   build: ./kudu
  #   ports: 
  #     - "8050:8050"
  #   stdin_open: true
  #   tty: true
  #   #command: service kudu-tserver start

  # spark:
  #   build: ./spark 
  #   volumes:
  #     - ./spark/data:/data/
  #   stdin_open: true
  #   tty: true
